default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  primary: &primary_development
    <<: *default
    database: veritas_development
  queue:
    <<: *primary_development
    database: veritas_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: veritas_test
  queue:
    <<: *primary_test
    database: veritas_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: veritas_production
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
  queue:
    <<: *primary_production
    database: veritas_production_queue
    migrations_paths: db/queue_migrate
