name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poppler
        run: |
          sudo apt-get update
          sudo apt -y install libpoppler-glib-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
  suggest_lint_changes:
    name: "Suggest lint changes"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poppler
        run: |
          sudo apt-get update
          sudo apt -y install libpoppler-glib-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install Yarn
        run: yarn install
      - name: Run Lint
        run: bin/lint -c
      - name: Comment suggested changes
        uses: parkerbxyz/suggest-changes@v2.0.0
        if: ${{ github.event.pull_request }}
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: yarn install
      - name: Run ESLint
        run: yarn lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: yarn install
      - name: Run Prettier
        run: yarn format:check
  zeitwerk:
    name: Zeitwerk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poppler
        run: |
          sudo apt-get update
          sudo apt -y install libpoppler-glib-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: JS package cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install JS packages
        run: |
          yarn install --pure-lockfile
      - name: Run zeitwerk:check
        env:
          RAILS_ENV: test
        run: bundle exec rails zeitwerk:check
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Brakeman
        run: bundle exec brakeman -q
